# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-23 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0025_auto_20170516_0158'),
        ('recurso_pr', '0003_auto_20170516_0158'),
    ]

    operations = [

    ]
