# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-23 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0025_auto_20170516_0158'),
        ('recurso_pr', '0003_auto_20170516_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaSolicitudEspecifica',
            fields=[
                ('lista_id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(default='', max_length=20)),
                ('recurso_reservado', models.IntegerField()),
                ('estado_reserva', models.CharField(choices=[('DI', 'Disponible'), ('EM', 'En Mantenimiento'), ('SO', 'Solicitado'), ('FU', 'Fuera de Uso'), ('EU', 'En Uso')], default='DI', max_length=2)),
                ('prioridad', models.CharField(default='', max_length=20)),
                ('fecha_reserva', models.DateField(default=django.utils.timezone.now)),
                ('hora_inicio', models.TimeField(default=django.utils.timezone.now)),
                ('hora_fin', models.TimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('solicitud_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField(default=django.utils.timezone.now)),
                ('hora_inicio', models.TimeField(default=django.utils.timezone.now)),
                ('hora_fin', models.TimeField(default=django.utils.timezone.now)),
                ('recurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recurso_pr.Recurso1')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Profile')),
            ],
        ),
    ]
