# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-24 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0025_auto_20170516_0158'),
        ('recurso_pr', '0003_auto_20170516_0158'),
        ('reserva_new', '0001_initial'),
    ]

    operations = [

    ]
