# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-25 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva_new', '0002_auto_20170524_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado_reserva',
            field=models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], max_length=20),
        ),
    ]
