# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recurso_pr', '0004_auto_20170530_1927'),
        ('usuario', '0028_auto_20170530_1927'),
        ('reserva_new', '0003_auto_20170525_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('lista_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_reserva', models.CharField(choices=[('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], max_length=20)),
                ('fecha_reserva', models.DateField(default=django.utils.timezone.now)),
                ('hora_inicio', models.TimeField(default=django.utils.timezone.now)),
                ('hora_fin', models.TimeField(default=django.utils.timezone.now)),
                ('recurso_reservado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recurso_pr.Recurso1')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('solicitud_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField(default=django.utils.timezone.now)),
                ('hora_inicio', models.TimeField(default=django.utils.timezone.now)),
                ('hora_fin', models.TimeField(default=django.utils.timezone.now)),
                ('recurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recurso_pr.Recurso1')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Profile')),
            ],
        ),
    ]
