# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recurso_pr', '0004_auto_20170530_1927'),
        ('usuario', '0028_auto_20170530_1927'),
        ('reserva_new', '0003_auto_20170525_1335'),
    ]

    operations = [


    ]
