# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva_new', '0004_reserva_solicitud'),
    ]

    operations = [

    ]
