# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva_new', '0006_auto_20170601_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='recurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recurso_pr.Recurso1'),
        ),
    ]
