# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 23:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserva_new', '0006_auto_20170601_1842'),
    ]

    operations = [

    ]
