# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-02 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva_new', '0007_auto_20170601_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado_reserva',
            field=models.CharField(choices=[('CONFIRMADA', 'CONFIRMADA'), ('CANCELADA', 'CANCELADA'), ('EN CURSO', 'EN CURSO'), ('FINALIZADA', 'FINALIZADA')], max_length=20),
        ),
    ]
