# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-10 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [


    ]
