# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recurso_pr', '0003_auto_20170516_0158'),
    ]

    operations = [


    ]
