# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recurso_pr', '0004_auto_20170530_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('ctra_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_caracteristica', models.CharField(max_length=80)),
                ('descripcion', models.TextField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DescripCarac',
            fields=[
                ('descripcion', models.TextField(default='', max_length=100)),
                ('desc_id', models.AutoField(primary_key=True, serialize=False)),
                ('ctra_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recurso_pr.Caracteristica')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso1',
            fields=[
                ('recurso_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(default='', max_length=300)),
                ('estado', models.CharField(choices=[('DI', 'Disponible'), ('RE', 'Reservado'), ('EM', 'En Mantenimiento'), ('FU', 'Fuera de Uso'), ('EU', 'En Uso')], default='DI', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='TipoRecurso1',
            fields=[
                ('tipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_recurso', models.CharField(max_length=80)),
                ('reservable', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='recurso1',
            name='tipo_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recurso_pr.TipoRecurso1'),
        ),
        migrations.AddField(
            model_name='descripcarac',
            name='recurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recurso_pr.Recurso1'),
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='tipo_recurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recurso_pr.TipoRecurso1'),
        ),
    ]
