# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-24 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurso_pr', '0005_auto_20170602_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso1',
            name='frecuencia',
            field=models.IntegerField(default=0),
        ),
    ]
