# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-24 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurso_pr', '0006_recurso1_frecuencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso1',
            name='frecuencia',
            field=models.CharField(default='', max_length=3),
        ),
    ]
