# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [


    ]
