# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 22:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [

        ('mantenimiento', '0001_initial'),
    ]

    operations = [

    ]
