# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 23:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0003_auto_20170425_2305'),
    ]

    operations = [

    ]
