# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 12:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0004_auto_20170425_2321'),
    ]

    operations = [

    ]
