# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-28 13:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0005_auto_20170428_1231'),
    ]

    operations = [

    ]
