# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0008_mantenimiento'),
    ]

    operations = [

    ]
