# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0008_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_entrega',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_fin',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
