# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 01:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0009_auto_20170504_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 1, 57, 17, 504502, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_fin',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 1, 57, 17, 504531, tzinfo=utc)),
        ),
    ]
