# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0009_auto_20170501_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='hora_entrega',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='mantenimiento',
            name='hora_fin',
            field=models.TextField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_entrega',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='fecha_fin',
            field=models.DateField(),
        ),
    ]
