# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 02:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0010_auto_20170502_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mantenimiento',
            name='resultado',
        ),
        migrations.AlterField(
            model_name='mantenimiento',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo')], default='', max_length=20),
        ),
    ]
