# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mantenimiento', '0016_mantenimiento'),
    ]

    operations = [

    ]
