# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0017_mantenimiento'),
    ]

    operations = [

    ]
