# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 15:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recurso_pr', '0002_auto_20170513_2127'),
        ('mantenimiento', '0018_auto_20170515_1529'),
    ]

    operations = [

    ]
