# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 12:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0019_mantenimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='hora_fin',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
