# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-16 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0020_mantenimiento'),
        ('mantenimiento', '0020_auto_20170516_1210'),
    ]

    operations = [
    ]
