# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recurso_pr', '0005_auto_20170602_1942'),
        ('mantenimiento', '0022_mantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('hora_entrega', models.TimeField(default=django.utils.timezone.now)),
                ('hora_fin', models.TimeField(default=django.utils.timezone.now)),
                ('tipo', models.CharField(blank=True, choices=[('Preventivo', 'Preventivo'), ('Correctivo', 'Correctivo')], default='', max_length=20)),
                ('recurso', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='recurso_pr.Recurso1')),
                ('tipo_recurso', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='recurso_pr.TipoRecurso1')),
            ],
        ),
    ]
