# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0023_mantenimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='estado_mant',
            field=models.CharField(choices=[('PENDIENTE', 'PENDIENTE'), ('EN CURSO', 'EN CURSO'), ('FINALIZADA', 'FINALIZADO')], default='PENDIENTE', max_length=20),
        ),
    ]
