# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0024_mantenimiento_estado_mant'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='observacion',
            field=models.CharField(default='', max_length=500),
        ),
    ]
