# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-23 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0025_mantenimiento_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='mantenimiento',
            name='estado_rec',
            field=models.CharField(choices=[('DI', 'Disponible'), ('FU', 'Fuera de Uso')], default='DI', max_length=2),
        ),
    ]
