# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0003_auto_20170422_1956'),
    ]

    operations = [

    ]
