# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0007_auto_20170423_1729'),
    ]

    operations = [


    ]
