# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 03:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0009_auto_20170423_1754'),
    ]

    operations = [

    ]
