# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0013_auto_20170506_2120'),
    ]

    operations = [


    ]
