# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0015_auto_20170513_2127'),
    ]

    operations = [

    ]
