# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cedula',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
