# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 02:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20170418_0134'),
    ]

    operations = [

    ]
