# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0003_auto_20170418_0202'),
    ]

    operations = [

    ]
