# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-21 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_auto_20170420_1342'),
    ]

    operations = [

    ]
