# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_auto_20170421_2150'),
    ]

    operations = [

    ]
