# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 20:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rol', '0009_auto_20170423_1754'),
        ('usuario', '0006_auto_20170423_1906'),
    ]

    operations = [


    ]
