# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 21:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20170423_2026'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UsuarioUser',
            new_name='Profile',
        ),
    ]
