# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 23:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20170423_2155'),
    ]

    operations = [

    ]
