# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-23 23:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_auto_20170423_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='cedula',
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
