# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-24 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_auto_20170423_2347'),
    ]

    operations = [

    ]
