# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_auto_20170424_1509'),
    ]

    operations = [

    ]
