# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-25 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_profile_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='categoria',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='usuario.CategoriaUsuario'),
        ),
    ]
