# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 21:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0010_auto_20170424_0330'),
        ('usuario', '0013_auto_20170425_0101'),
    ]

    operations = [

    ]
