# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 04:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0011_auto_20170505_0459'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0014_auto_20170505_0121'),
    ]

    operations = [

    ]
