# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 19:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0015_auto_20170426_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rol.UserRol'),
        ),
    ]
