# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 21:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0013_auto_20170506_2120'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0016_auto_20170506_2021'),
    ]

    operations = [

    ]
