# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-27 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0010_auto_20170424_0330'),
        ('usuario', '0017_auto_20170426_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='rol',
        ),
        migrations.AddField(
            model_name='profile',
            name='rol',
            field=models.ManyToManyField(to='rol.UserRol'),
        ),
    ]
