# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 21:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0014_auto_20170512_2110'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0017_auto_20170506_2120'),
    ]

    operations = [

    ]
