# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 21:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0015_auto_20170513_2127'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0021_auto_20170513_2117'),
    ]

    operations = [


    ]
