# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0022_auto_20170513_2127'),
    ]

    operations = [

    ]
