# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 02:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0023_auto_20170513_2142'),
    ]

    operations = [

    ]
