# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 01:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0016_auto_20170516_0158'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0024_auto_20170514_0208'),
    ]

    operations = [

    ]
