# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-27 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0025_auto_20170516_0158'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriausuario',
            name='prioridad',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='categoriausuario',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='categoria',
            field=models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='usuario.CategoriaUsuario'),
        ),
    ]
