# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 19:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0026_auto_20170527_1909'),
    ]

    operations = [

    ]
