# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 19:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0017_auto_20170530_1927'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0027_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('prioridad', models.IntegerField(default=0, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(default='', max_length=20, unique=True)),
                ('direccion', models.CharField(default='', max_length=50)),
                ('telefono', models.CharField(default='', max_length=50)),
                ('categoria', models.ForeignKey(max_length=30, on_delete=django.db.models.deletion.CASCADE, to='usuario.CategoriaUsuario')),
                ('rol', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rol.UserRol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telefono',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 5, 30)),
        ),
    ]
