# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-30 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0028_auto_20170530_1927'),
    ]

    operations = [

    ]
