# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-31 02:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0029_auto_20170530_2147'),
    ]

    operations = [

    ]
