# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 12:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0030_auto_20170531_0255'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoriaUsuario',
        ),
        migrations.AlterField(
            model_name='profile',
            name='categoria',
            field=models.IntegerField(choices=[(1, 'Institucional'), (2, 'Titular'), (3, 'Adjunto'), (4, 'Asistente'), (5, 'Encargado de Catedra'), (6, 'Auxiliar de Ensenanza'), (7, 'Alumno'), (8, 'Funcionario')], default=8),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 6, 1)),
        ),
    ]
