# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 12:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0030_auto_20170531_0255'),
    ]

    operations = [

    ]
