# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 19:42
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0018_auto_20170602_1942'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0032_auto_20170602_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(default='', max_length=20, unique=True)),
                ('direccion', models.CharField(default='', max_length=50)),
                ('telefono', models.CharField(default='', max_length=50)),
                ('categoria', models.IntegerField(choices=[(1, 'Institucional'), (2, 'Titular'), (3, 'Adjunto'), (4, 'Asistente'), (5, 'Encargado de Catedra'), (6, 'Auxiliar de Ensenanza'), (7, 'Alumno'), (8, 'Funcionario')], default=8)),
                ('rol', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='rol.UserRol')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telefono',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activation_key',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 6, 2)),
        ),
    ]
