# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-03 02:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0033_auto_20170602_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 6, 3)),
        ),
    ]
