# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-14 01:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0034_auto_20170603_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 6, 14)),
        ),
    ]
