# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0035_auto_20170614_0107'),
        ('usuario', '0035_auto_20170620_2017'),
    ]

    operations = [
    ]
