# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 03:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [

    ]
