# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 13:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_auto_20170427_0312'),
    ]

    operations = [

    ]
