# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 16:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reserva', '0006_listareservageneral_reservageneral'),
        ('recurso', '0018_auto_20170427_1635'),
        ('usuario', '0014_categoriausuario_profile'),
    ]

    operations = [


    ]
