# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 19:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [

        ('reserva', '0007_auto_20170427_1635'),
    ]

    operations = [


    ]
