# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 01:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recurso', '0022_auto_20170429_0114'),
        ('usuario', '0014_categoriausuario_profile'),
        ('reserva', '0010_auto_20170429_0024'),
    ]

    operations = [

    ]
