# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 02:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recurso', '0023_auto_20170501_0232'),
        ('usuario', '0014_categoriausuario_profile'),
        ('reserva', '0011_listareservageneral_reservageneral'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaReservaGeneral',
            fields=[
                ('lista_id', models.AutoField(primary_key=True, serialize=False)),
                ('recurso_reservado', models.IntegerField()),
                ('estado_reserva', models.CharField(choices=[('DI', 'Disponible'), ('RE', 'Reservado'), ('EM', 'En Mantenimiento'), ('SO', 'Solicitado'), ('FU', 'Fuera de Uso'), ('EU', 'En Uso')], default='DI', max_length=2)),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField(default=datetime.datetime(2017, 5, 1, 2, 32, 16, 944408, tzinfo=utc))),
                ('hora_fin', models.TimeField(default=datetime.datetime(2017, 5, 1, 2, 32, 16, 944435, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='ReservaGeneral',
            fields=[
                ('reserva_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField(default=datetime.datetime(2017, 5, 1, 2, 32, 16, 943688, tzinfo=utc))),
                ('hora_fin', models.TimeField(default=datetime.datetime(2017, 5, 1, 2, 32, 16, 943722, tzinfo=utc))),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Profile')),
                ('recurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recurso.Recurso1')),
            ],
        ),
    ]
