# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 05:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0024_auto_20170501_0522'),
        ('usuario', '0014_categoriausuario_profile'),
        ('reserva', '0012_listareservageneral_reservageneral'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaReservaEspecifica',
            fields=[
                ('lista_id', models.AutoField(primary_key=True, serialize=False)),
                ('recurso_reservado', models.IntegerField()),
                ('estado_reserva', models.CharField(choices=[('DI', 'Disponible'), ('RE', 'Reservado'), ('EM', 'En Mantenimiento'), ('SO', 'Solicitado'), ('FU', 'Fuera de Uso'), ('EU', 'En Uso')], default='DI', max_length=2)),
                ('prioridad', models.CharField(max_length=50)),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField(default=datetime.datetime(2017, 5, 1, 5, 22, 1, 56161, tzinfo=utc))),
                ('hora_fin', models.TimeField(default=datetime.datetime(2017, 5, 1, 5, 22, 1, 56190, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='ReservaEspecifica',
            fields=[
                ('reserva_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField(default=datetime.datetime(2017, 5, 1, 5, 22, 1, 55427, tzinfo=utc))),
                ('hora_fin', models.TimeField(default=datetime.datetime(2017, 5, 1, 5, 22, 1, 55453, tzinfo=utc))),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Profile')),
                ('recurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recurso.Recurso1')),
            ],
        ),
        migrations.AlterField(
            model_name='listareservageneral',
            name='hora_fin',
            field=models.TimeField(default=datetime.datetime(2017, 5, 1, 5, 22, 1, 54801, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listareservageneral',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2017, 5, 1, 5, 22, 1, 54773, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservageneral',
            name='hora_fin',
            field=models.TimeField(default=datetime.datetime(2017, 5, 1, 5, 22, 1, 54072, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservageneral',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2017, 5, 1, 5, 22, 1, 54042, tzinfo=utc)),
        ),
    ]
