# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 05:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [

        ('reserva', '0012_listareservageneral_reservageneral'),
    ]

    operations = [

    ]
