# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-01 23:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0014_listareservaespecifica_listareservageneral_reservaespecifica_reservageneral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listareservaespecifica',
            name='hora_fin',
            field=models.TimeField(default=datetime.datetime(2017, 5, 1, 23, 45, 10, 607305, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listareservaespecifica',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2017, 5, 1, 23, 45, 10, 607260, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listareservageneral',
            name='hora_fin',
            field=models.TimeField(default=datetime.datetime(2017, 5, 1, 23, 45, 10, 605218, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listareservageneral',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2017, 5, 1, 23, 45, 10, 605174, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservaespecifica',
            name='hora_fin',
            field=models.TimeField(default=datetime.datetime(2017, 5, 1, 23, 45, 10, 606208, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservaespecifica',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2017, 5, 1, 23, 45, 10, 606165, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservageneral',
            name='hora_fin',
            field=models.TimeField(default=datetime.datetime(2017, 5, 1, 23, 45, 10, 603949, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='reservageneral',
            name='hora_inicio',
            field=models.TimeField(default=datetime.datetime(2017, 5, 1, 23, 45, 10, 603899, tzinfo=utc)),
        ),
    ]
