# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 01:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0013_auto_20170425_0101'),
        ('recurso', '0027_auto_20170504_0157'),
        ('reserva', '0015_auto_20170504_0139'),
    ]

    operations = [

    ]
