# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 01:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0013_auto_20170425_0101'),
        ('recurso', '0027_auto_20170504_0157'),
        ('reserva', '0015_auto_20170504_0139'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaReservaEspecifica',
            fields=[
                ('lista_id', models.AutoField(primary_key=True, serialize=False)),
                ('recurso_reservado', models.IntegerField()),
                ('estado_reserva', models.CharField(choices=[('DI', 'Disponible'), ('RE', 'Reservado'), ('EM', 'En Mantenimiento'), ('SO', 'Solicitado'), ('FU', 'Fuera de Uso'), ('EU', 'En Uso')], default='DI', max_length=2)),
                ('prioridad', models.IntegerField()),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField(default=datetime.datetime(2017, 5, 4, 1, 57, 17, 512587, tzinfo=utc))),
                ('hora_fin', models.TimeField(default=datetime.datetime(2017, 5, 4, 1, 57, 17, 512612, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='ListaReservaGeneral',
            fields=[
                ('lista_id', models.AutoField(primary_key=True, serialize=False)),
                ('recurso_reservado', models.IntegerField()),
                ('estado_reserva', models.CharField(choices=[('DI', 'Disponible'), ('RE', 'Reservado'), ('EM', 'En Mantenimiento'), ('SO', 'Solicitado'), ('FU', 'Fuera de Uso'), ('EU', 'En Uso')], default='DI', max_length=2)),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField(default=datetime.datetime(2017, 5, 4, 1, 57, 17, 511231, tzinfo=utc))),
                ('hora_fin', models.TimeField(default=datetime.datetime(2017, 5, 4, 1, 57, 17, 511259, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='ReservaEspecifica',
            fields=[
                ('reserva_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField(default=datetime.datetime(2017, 5, 4, 1, 57, 17, 511873, tzinfo=utc))),
                ('hora_fin', models.TimeField(default=datetime.datetime(2017, 5, 4, 1, 57, 17, 511899, tzinfo=utc))),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Profile')),
                ('recurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recurso.Recurso1')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaGeneral',
            fields=[
                ('reserva_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField(default=datetime.datetime(2017, 5, 4, 1, 57, 17, 510464, tzinfo=utc))),
                ('hora_fin', models.TimeField(default=datetime.datetime(2017, 5, 4, 1, 57, 17, 510497, tzinfo=utc))),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Profile')),
                ('recurso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recurso.Recurso1')),
            ],
        ),
    ]
