# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-02 01:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0015_auto_20170501_2345'),
    ]

    operations = [

    ]
