# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0018_auto_20170504_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listareservaespecifica',
            name='fecha_reserva',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservaespecifica',
            name='fecha_reserva',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='reservageneral',
            name='fecha_reserva',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
