# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0018_auto_20170504_1835'),
    ]

    operations = [

    ]
