# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-05 04:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [

        ('usuario', '0015_auto_20170505_0459'),
        ('reserva', '0019_auto_20170504_1835'),
    ]

    operations = [

    ]
