# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0019_auto_20170504_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listareservaespecifica',
            name='fecha_reserva',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='listareservageneral',
            name='fecha_reserva',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservaespecifica',
            name='fecha_reserva',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservageneral',
            name='fecha_reserva',
            field=models.DateField(),
        ),
    ]
