# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-05 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [

        ('usuario', '0015_auto_20170505_0459'),
        ('reserva', '0020_listareservaespecifica_listareservageneral_reservaespecifica_reservageneral'),
    ]

    operations = [


    ]
