# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-13 21:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recurso_pr', '0002_auto_20170513_2127'),
        ('usuario', '0022_auto_20170513_2127'),
        ('reserva', '0025_auto_20170512_2203'),
    ]

    operations = [


    ]
