# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 00:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0027_remove_listareservaespecifica_reserva_id'),
    ]

    operations = [

    ]
