# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 01:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recurso_pr', '0003_auto_20170516_0158'),
        ('usuario', '0025_auto_20170516_0158'),
        ('reserva', '0028_listareservageneral_usuario'),
    ]

    operations = [

    ]
