# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-21 23:14
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tipo', models.IntegerField(default=0)),
                ('nombre_rec', models.CharField(max_length=50)),
                ('reservable', models.BooleanField(default=True)),
                ('fecha_man', models.DateTimeField(default=django.utils.timezone.now)),
                ('caracteristicas', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='nombre_rec',
        ),
        migrations.AddField(
            model_name='recurso',
            name='estado',
            field=models.CharField(default='Disponible', max_length=50),
        ),
        migrations.AddField(
            model_name='recurso',
            name='estados',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=['Disponible', 'Reservado', 'En mantenimiento', 'Solicitado', 'Fuera de uso', 'En uso'], size=None),
        ),
        migrations.AddField(
            model_name='recurso',
            name='tipo_rec',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='recurso.TipoRecurso'),
        ),
    ]
