# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 20:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0003_remove_recurso_estados'),
    ]

    operations = [

    ]
