# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 21:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0004_auto_20170424_2044'),
    ]

    operations = [

    ]
