# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 22:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0005_auto_20170424_2145'),
    ]

    operations = [

    ]
