# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 00:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0006_auto_20170424_2212'),
    ]

    operations = [


    ]
