# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 19:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0011_auto_20170425_1803'),
    ]

    operations = [

    ]
