# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 19:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0018_auto_20170427_1635'),
    ]

    operations = [

    ]
