# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 00:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0019_auto_20170428_1941'),
    ]

    operations = [

    ]
