# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-29 01:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0021_auto_20170429_0024'),
    ]

    operations = [

    ]
