# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 02:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recurso', '0022_auto_20170429_0114'),
    ]

    operations = [

    ]
