# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 01:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0026_auto_20170504_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiporecurso1',
            name='fecha_mantenimiento',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 4, 1, 57, 17, 503254, tzinfo=utc)),
        ),
    ]
