# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-04 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recurso', '0027_auto_20170502_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiporecurso1',
            name='fecha_mantenimiento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
