# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recurso', '0028_auto_20170504_1513'),
    ]

    operations = [


    ]
